version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=simpler_test
      - DB_HOST=db
      - DB_PASSWORD=simplePassword2!
      - DB_USER=simpler
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "simpler"
      POSTGRES_PASSWORD: "simplePassword2!"
      POSTGRES_DB: "simpler_test"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: